name: Publish NuGet

on:
  release:
    types: [published]

permissions:
  contents: read
  id-token: write

jobs:
  publish-nuget:
    name: Pack & Publish NuGet
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Test
        run: dotnet test --configuration Release
        working-directory: BallisticSolutions

      - name: Pack
        run: dotnet pack --no-restore --configuration Release --output artifacts
        working-directory: BallisticSolutions

      - name: NuGet login (Trusted Publishing)
        uses: NuGet/login@v1
        id: login
        with:
          user: ${{ secrets.NUGET_USER }}

      - name: NuGet push
        run: dotnet nuget push artifacts/*.nupkg --api-key ${{ steps.login.outputs.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
        working-directory: BallisticSolutions
